import type { ExportScope, FamilyData, PageFormat, TemplateId } from "./types";
import { scopeData } from "./tree-filter";
import { mountTree } from "./chart";

const MM_TO_PX = 96 / 25.4;

const PAGES: Record<PageFormat, { orientation: "landscape" | "portrait"; w: number; h: number; label: string }> = {
  "a3-landscape": { orientation: "landscape", w: 420, h: 297, label: "A3 landscape" },
  "a4-portrait": { orientation: "portrait", w: 210, h: 297, label: "A4 portrait" },
};

const PAGE_BG: Record<TemplateId, string> = { classic: "#faf6ee", minimal: "#ffffff", madhubani: "#f3e2b3" };
const INK: Record<TemplateId, [number, number, number]> = {
  classic: [58, 47, 34],
  minimal: [17, 17, 17],
  madhubani: [31, 42, 92],
};

export const SCOPE_LABEL: Record<ExportScope, string> = {
  full: "Full family tree",
  paternal: "Paternal lineage (Panji-style)",
};

export interface ExportOptions {
  data: FamilyData;
  scope: ExportScope;
  template: TemplateId;
  format: PageFormat;
  onProgress?: (msg: string) => void;
  /** true for the built-in fictional demo family (adds a disclaimer to the footer) */
  sample?: boolean;
}

const hex = (c: string) => [1, 3, 5].map((i) => parseInt(c.slice(i, i + 2), 16)) as [number, number, number];

export async function exportTreePdf({ data, scope, template, format, onProgress, sample }: ExportOptions) {
  const [{ default: html2canvas }, { jsPDF }, QR] = await Promise.all([
    import("html2canvas"),
    import("jspdf"),
    import("qrcode"),
  ]);
  const page = PAGES[format];
  const margin = 8; // mm
  const headerH = 20;
  const footerH = 22;
  const areaW = page.w - margin * 2;
  const areaH = page.h - margin * 2 - headerH - footerH;

  onProgress?.("Laying out tree…");
  const host = document.createElement("div");
  host.style.cssText = `position:fixed;left:-100000px;top:0;width:${Math.round(areaW * MM_TO_PX)}px;height:${Math.round(areaH * MM_TO_PX)}px;pointer-events:none;`;
  document.body.appendChild(host);

  try {
    const scoped = scopeData(data, scope);
    const mounted = await mountTree(host, scoped, template, {
      rootId: data.root_person_id,
      transition: 0,
      exporting: true,
      inset: template === "madhubani" ? [84, 40] : [36, 36],
    });
    await mounted.settled();
    await (document as Document & { fonts?: { ready: Promise<unknown> } }).fonts?.ready;

    onProgress?.("Rendering…");
    const canvas = await html2canvas(mounted.frame, {
      scale: 2,
      backgroundColor: PAGE_BG[template],
      logging: false,
      useCORS: true,
    });

    onProgress?.("Building PDF…");
    const doc = new jsPDF({ orientation: page.orientation, unit: "mm", format: format === "a3-landscape" ? "a3" : "a4" });
    const [br, bg, bb] = hex(PAGE_BG[template]);
    doc.setFillColor(br, bg, bb);
    doc.rect(0, 0, page.w, page.h, "F");

    const ink = INK[template];
    doc.setTextColor(...ink);
    const root = data.persons.find((p) => p.person_id === data.root_person_id);
    doc.setFont(template === "madhubani" ? "times" : "helvetica", "bold");
    doc.setFontSize(page.w > 300 ? 22 : 17);
    doc.text(`${root?.name_roman ?? "Family"} — ${SCOPE_LABEL[scope]}`, margin + 2, margin + 11);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(page.w > 300 ? 10 : 8.5);
    const people = scoped.persons.length;
    doc.text(
      `${people} people · ${template === "madhubani" ? "Mithila Madhubani" : template === "classic" ? "Classic" : "Modern Minimal"} template · ${page.label}`,
      margin + 2,
      margin + 17,
    );

    doc.addImage(canvas.toDataURL("image/jpeg", 0.95), "JPEG", margin, margin + headerH, areaW, areaH);

    // footer: project URL + QR back to the owner's tree
    const url = window.location.origin;
    const qr = await QR.toDataURL(url, { margin: 1, width: 240, color: { dark: "#111111", light: "#ffffff" } });
    const qrSize = footerH - 4;
    doc.addImage(qr, "PNG", page.w - margin - qrSize, page.h - margin - footerH + 2, qrSize, qrSize);
    doc.setFontSize(page.w > 300 ? 10 : 8.5);
    doc.setTextColor(...ink);
    doc.text(window.location.host, margin + 2, page.h - margin - 10);
    doc.setFontSize(page.w > 300 ? 8.5 : 7);
    doc.text(
      sample ? "Sample (fictional) family shown — preview. Generated by Maithil Panji." : "Generated by Maithil Panji.",
      margin + 2,
      page.h - margin - 5,
    );

    const file = `family-tree-${scope}-${template}-${format}.pdf`;
    doc.save(file);
    mounted.destroy();
    return file;
  } finally {
    host.remove();
  }
}
