import type { ExportScope, FamilyData, PageFormat, PosterPaper, TemplateId } from "./types";
import { outsideChart, scopeData } from "./tree-filter";
import { measureTree, mountTree, type MountedTree } from "./chart";

const MM_TO_PX = 96 / 25.4;
const PX_MM = 25.4 / 96;

const PAGES: Record<PageFormat, { orientation: "landscape" | "portrait"; w: number; h: number; label: string }> = {
  "a3-landscape": { orientation: "landscape", w: 420, h: 297, label: "A3 landscape" },
  "a4-portrait": { orientation: "portrait", w: 210, h: 297, label: "A4 portrait" },
};

const PAGE_BG: Record<TemplateId, string> = { classic: "#faf6ee", minimal: "#ffffff", madhubani: "#f3e2b3" };
const INK: Record<TemplateId, [number, number, number]> = {
  classic: [58, 47, 34],
  minimal: [17, 17, 17],
  madhubani: [31, 42, 92],
};

export const SCOPE_LABEL: Record<ExportScope, string> = {
  full: "Full family tree — my line",
  paternal: "Paternal lineage (Panji-style)",
  all: "Whole family chart",
};

/** standard sheets for a print shop, in mm (portrait) */
export const PAPER_MM: Record<Exclude<PosterPaper, "auto">, { w: number; h: number; label: string }> = {
  a2: { w: 420, h: 594, label: "A2" }, a1: { w: 594, h: 841, label: "A1" }, a0: { w: 841, h: 1189, label: "A0" },
};
const CHROME_FOOT = (viewUrl: boolean) => (viewUrl ? 28 : 22);
/**
 * How a tree of W × H pixels sits on a standard sheet: the sheet (landscape for a wide tree), and how many mm one tree pixel gets.
 * A card is about 165 px wide, so `cardMm` tells how big the names will print.
 */
export function paperFit(paper: Exclude<PosterPaper, "auto">, W: number, H: number, hasQr: boolean) {
  const p = PAPER_MM[paper];
  const landscape = W >= H;
  const pw = landscape ? p.h : p.w, ph = landscape ? p.w : p.h;
  const u = Math.max(1, pw / 420);
  const aw = pw - 16 * u, ah = ph - 16 * u - 20 * u - CHROME_FOOT(hasQr) * u;
  const mmPerPx = Math.min(aw / W, ah / H, 0.35);
  return { pw, ph, u, mmPerPx, cardMm: Math.round(165 * mmPerPx), landscape };
}

export type ExportMode = "fit" | "pages" | "poster";

export interface ExportOptions {
  data: FamilyData;
  scope: ExportScope;
  template: TemplateId;
  format: PageFormat;
  /** fit = everything on one page (small trees); pages = readable size over several A3/A4 sheets; poster = one very large page for a print shop or screen zoom */
  mode?: ExportMode;
  onProgress?: (msg: string) => void;
  /** poster mode only: one custom large page (default) or a standard A2 / A1 / A0 sheet */
  paper?: PosterPaper;
  /** true for the built-in fictional demo family (adds a disclaimer to the footer) */
  sample?: boolean;
  /** read-only online address of this tree; when given, the footer QR code opens it (otherwise the QR opens the home page) */
  viewUrl?: string;
}

/** "Fit" stays readable up to about this many people; beyond it the sheet is too small to read. */
export const FIT_MAX_PEOPLE = 40;

const hex = (c: string) => [1, 3, 5].map((i) => parseInt(c.slice(i, i + 2), 16)) as [number, number, number];
const INSET: Record<TemplateId, [number, number]> = { madhubani: [84, 40], classic: [36, 36], minimal: [36, 36] };
const TPL_NAME: Record<TemplateId, string> = { madhubani: "Mithila Madhubani", classic: "Classic", minimal: "Modern Minimal" };

type Html2Canvas = typeof import("html2canvas").default;

function offscreenHost(w: number, h: number) {
  const host = document.createElement("div");
  host.style.cssText = `position:fixed;left:-100000px;top:0;width:${Math.round(w)}px;height:${Math.round(h)}px;pointer-events:none;`;
  document.body.appendChild(host);
  return host;
}

export async function exportTreePdf({ data, scope, template, format, mode = "fit", paper = "auto", onProgress, sample, viewUrl }: ExportOptions) {
  const [{ default: html2canvas }, { jsPDF }, QR] = await Promise.all([import("html2canvas"), import("jspdf"), import("qrcode")]);
  const scoped = scopeData(data, scope);
  const root = data.persons.find((p) => p.person_id === data.root_person_id);
  const title = `${root?.name_roman ?? "Family"} — ${SCOPE_LABEL[scope]}`;
  const [br, bg, bb] = hex(PAGE_BG[template]);
  const ink = INK[template];
  const qr = await QR.toDataURL(viewUrl || window.location.origin, { errorCorrectionLevel: "M", margin: 1, width: 240, color: { dark: "#111111", light: "#ffffff" } });
  // the PAAG mark in the corner of every page (skipped quietly if it cannot be loaded)
  const mark = await fetch("/brand/paag-mark-192.png").then((r) => (r.ok ? r.blob() : Promise.reject(new Error("mark")))).then((b) => new Promise<string>((ok, no) => { const fr = new FileReader(); fr.onload = () => ok(String(fr.result)); fr.onerror = () => no(fr.error); fr.readAsDataURL(b); })).catch(() => null);
  const measured = await measureTree(scoped);
  const shown = measured.shown;
  const people = shown.length; // the people the chart really draws
  const footerNote = sample ? "Sample (fictional) family shown — preview. Generated by Maithil Panji (PAAG Foundation) · paag.org.in." : "Generated by Maithil Panji (PAAG Foundation) · paag.org.in.";
  const fontsReady = () => (document as Document & { fonts?: { ready: Promise<unknown> } }).fonts?.ready;

  /** header + footer for a page of w × h mm; `u` scales the type for very large pages. Returns the free area. */
  const chrome = (doc: InstanceType<typeof jsPDF>, w: number, h: number, u: number, subtitle: string, small = false) => {
    const margin = 8 * u, headerH = (small ? 14 : 20) * u, footerH = (small ? 10 : viewUrl ? 28 : 22) * u;
    doc.setFillColor(br, bg, bb);
    doc.rect(0, 0, w, h, "F");
    doc.setTextColor(...ink);
    doc.setFont(template === "madhubani" ? "times" : "helvetica", "bold");
    doc.setFontSize((w > 300 ? 22 : 17) * u * (small ? 0.7 : 1));
    doc.text(title, margin + 2 * u, margin + (small ? 7 : 11) * u);
    if (mark) { const m = (small ? 9 : 14) * u; doc.addImage(mark, "PNG", w - margin - m, margin, m, m); }
    doc.setFont("helvetica", "normal");
    doc.setFontSize((w > 300 ? 10 : 8.5) * u * (small ? 0.8 : 1));
    doc.text(subtitle, margin + 2 * u, margin + (small ? 12 : 17) * u);
    if (small) {
      doc.setFontSize(7.5 * u);
      doc.text(`${window.location.host} · ${footerNote}`, margin + 2 * u, h - margin);
    } else {
      const qrSize = footerH - 4 * u;
      doc.addImage(qr, "PNG", w - margin - qrSize, h - margin - footerH + 2 * u, qrSize, qrSize);
      doc.setFontSize((w > 300 ? 10 : 8.5) * u);
      doc.text(viewUrl ? "Scan the code to see this family tree online" : window.location.host, margin + 2 * u, h - margin - 10 * u);
      doc.setFontSize((w > 300 ? 8.5 : 7) * u);
      doc.text(viewUrl ? `${window.location.host} · ${footerNote}` : footerNote, margin + 2 * u, h - margin - 5 * u);
    }
    return { x: margin, y: margin + headerH, w: w - margin * 2, h: h - margin * 2 - headerH - footerH };
  };

  /** html2canvas copies the styles of the WHOLE page for every picture it takes; leave out everything that is not the tree being drawn */
  const onlyThe = (frame: HTMLElement) => (el: Element) => {
    if (!document.body.contains(el)) return false;
    return !(el === frame || frame.contains(el) || el.contains(frame));
  };

  /** the whole tree squeezed onto one page */
  const renderFit = async (areaW: number, areaH: number) => {
    const host = offscreenHost(areaW * MM_TO_PX, areaH * MM_TO_PX);
    try {
      const mounted = await mountTree(host, scoped, template, { rootId: data.root_person_id, transition: 0, exporting: true, inset: INSET[template] });
      await mounted.settled(); await fontsReady();
      const canvas = await html2canvas(mounted.frame, { scale: 2, backgroundColor: PAGE_BG[template], logging: false, useCORS: true, ignoreElements: onlyThe(mounted.frame) });
      mounted.destroy();
      return canvas.toDataURL("image/jpeg", 0.95);
    } finally { host.remove(); }
  };

  /** the tree at 100 % in an off-screen frame, drawn once; tiles are cut from it one at a time (keeps memory low, also on phones) */
  const withNatural = async <T,>(fn: (n: { frame: HTMLElement; W: number; H: number; tile: (x: number, y: number, w: number, h: number, scale: number) => Promise<string> }) => Promise<T>) => {
    const m = await measureTree(scoped);
    const [iv, ih] = INSET[template];
    const W = m.width + ih * 2 + 60, H = m.height + iv * 2 + 60;
    const host = offscreenHost(W, H);
    let mounted: MountedTree | undefined;
    try {
      mounted = await mountTree(host, scoped, template, { rootId: data.root_person_id, transition: 0, exporting: true, inset: [iv, ih] });
      await mounted.settled(); await fontsReady();
      const frame = mounted.frame;
      // note where every card and link sits; a tile then drops everything outside itself, which keeps big families fast
      const fr = frame.getBoundingClientRect();
      frame.querySelectorAll(".card_cont, path.link, .pj-leaves path").forEach((el) => {
        const r = el.getBoundingClientRect();
        el.setAttribute("data-r", [r.left - fr.left, r.top - fr.top, r.right - fr.left, r.bottom - fr.top].map(Math.round).join(","));
      });
      const tile = async (x: number, y: number, w: number, h: number, scale: number) => {
        const M = 160;
        // html2canvas copies the styles of every node it clones, which is what makes a big family slow:
        // so everything outside this tile is taken out of the live page first, and put back afterwards
        const taken: Array<{ el: Element; parent: Node; next: Node | null }> = [];
        frame.querySelectorAll("[data-r]").forEach((el) => {
          const [x0, y0, x1, y1] = (el.getAttribute("data-r") ?? "").split(",").map(Number) as [number, number, number, number];
          if ((x1 < x - M || x0 > x + w + M || y1 < y - M || y0 > y + h + M) && el.parentNode) taken.push({ el, parent: el.parentNode, next: el.nextSibling });
        });
        for (const t of taken) t.parent.removeChild(t.el);
        let c: HTMLCanvasElement;
        try {
        c = await (html2canvas as Html2Canvas)(frame, {
          x, y, width: w, height: h, scale, backgroundColor: PAGE_BG[template], logging: false, useCORS: true, windowWidth: W, windowHeight: H, ignoreElements: onlyThe(frame),
          onclone: (doc) => {
            // the link drawing is one SVG as big as the whole chart: shrink it to this tile (the cost of rasterising it dominates otherwise)
            const svg = doc.querySelector<SVGSVGElement>("svg.main_svg");
            const view = svg?.querySelector<SVGGElement>(".view");
            const m = /translate\(([-\d.]+)px,\s*([-\d.]+)px\)\s*scale\(([-\d.]+)\)/.exec(view?.getAttribute("style") ?? "");
            if (svg && view && m) {
              const left = x - M - ih, top = y - M - iv;
              svg.style.cssText = `position:absolute;left:${left}px;top:${top}px;width:${w + 2 * M}px;height:${h + 2 * M}px;`;
              svg.querySelector("rect")?.setAttribute("width", String(w + 2 * M));
              svg.querySelector("rect")?.setAttribute("height", String(h + 2 * M));
              view.setAttribute("style", `transform: translate(${+m[1]! - left}px, ${+m[2]! - top}px) scale(${m[3]});`);
            }
            // the triangle bands along the top and bottom are as wide as the chart too: keep only the part this tile shows
            // (the pattern repeats every 22 px, so starting on a multiple of 22 keeps neighbouring tiles lined up)
            doc.querySelectorAll<HTMLElement>(".pj-deco > div").forEach((d) => {
              if (d.style.height !== "16px") return;
              const lo = Math.max(16, x - M), hi = Math.min(W - 16, x + w + M);
              const L = 16 + 22 * Math.floor((lo - 16) / 22);
              d.style.left = `${L}px`; d.style.right = "auto"; d.style.width = `${Math.max(0, hi - L)}px`;
            });
          },
        });
        } finally {
          for (let i = taken.length - 1; i >= 0; i--) { const t = taken[i]!; t.parent.insertBefore(t.el, t.next); }
        }
        return c.toDataURL("image/jpeg", 0.92);
      };
      return await fn({ frame, W, H, tile });
    } finally { mounted?.destroy(); host.remove(); }
  };

  /** an extra A4 page for people who belong to other families' charts (only in the whole-family chart) */
  const outsidePage = async (doc: InstanceType<typeof jsPDF>, shownIds: string[]) => {
    if (scope !== "all") return;
    const list = outsideChart(data, new Set(shownIds));
    if (!list.length) return;
    let first = true, y = 0;
    const page = () => {
      doc.addPage([210, 297], "portrait");
      doc.setFillColor(br, bg, bb); doc.rect(0, 0, 210, 297, "F");
      doc.setTextColor(...ink);
      doc.setFont("helvetica", "bold"); doc.setFontSize(14); doc.text(first ? "Also in this family tree" : "Also in this family tree (continued)", 14, 20);
      if (first) {
        doc.setFont("helvetica", "normal"); doc.setFontSize(9);
        doc.text(doc.splitTextToSize("These people are recorded in the tree but are not drawn on the chart, because they belong to other families' charts (for example the parents of a wife).", 182), 14, 27);
      }
      first = false; y = 40;
    };
    page();
    doc.setFontSize(9);
    for (const r of list) {
      if (y > 280) page();
      doc.setFont("helvetica", "bold"); doc.text(r.name, 14, y);
      doc.setFont("helvetica", "normal"); doc.text([r.years, r.village].filter(Boolean).join(" · "), 90, y); doc.text(r.note, 128, y, { maxWidth: 70 });
      y += 6;
    }
  };

  const tag = `${scope}-${template}`;
  const subtitle = (extra: string) => `${people} people · ${TPL_NAME[template]} template${extra ? ` · ${extra}` : ""}`;

  /* ───── one page ───── */
  if (mode === "fit") {
    const page = PAGES[format];
    onProgress?.("Laying out tree…");
    const doc = new jsPDF({ orientation: page.orientation, unit: "mm", format: format === "a3-landscape" ? "a3" : "a4" });
    const area = chrome(doc, page.w, page.h, 1, subtitle(page.label));
    onProgress?.("Rendering…");
    const img = await renderFit(area.w, area.h);
    doc.addImage(img, "JPEG", area.x, area.y, area.w, area.h);
    await outsidePage(doc, shown);
    const file = `family-tree-${tag}-${format}.pdf`;
    doc.save(file);
    return file;
  }

  /* ───── several A3 / A4 sheets at a readable size ───── */
  if (mode === "pages") {
    const page = PAGES[format];
    const doc = new jsPDF({ orientation: page.orientation, unit: "mm", format: format === "a3-landscape" ? "a3" : "a4", compress: true });
    const file = `family-tree-${tag}-${format}-parts.pdf`;
    await withNatural(async ({ W, H, tile }) => {
      // the largest size that keeps the job to about a dozen sheets (never smaller than 55 %)
      const probe = chrome(new jsPDF({ orientation: page.orientation, unit: "mm", format: format === "a3-landscape" ? "a3" : "a4" }), page.w, page.h, 1, "", true);
      let k = 1;
      const grid = (kk: number) => ({ cols: Math.ceil((W * kk * PX_MM) / probe.w), rows: Math.ceil((H * kk * PX_MM) / probe.h) });
      while (k > 0.55 && grid(k).cols * grid(k).rows > 12) k = Math.round((k - 0.05) * 100) / 100;
      const { cols, rows } = grid(k);
      const tw = probe.w / (PX_MM * k), th = probe.h / (PX_MM * k); // tile size in tree pixels
      const total = cols * rows;

      // page 1: the overview, with a guide to joining the parts
      onProgress?.("Overview…");
      const a = chrome(doc, page.w, page.h, 1, subtitle(`overview · printed in ${total} parts at ${Math.round(k * 100)}%`));
      doc.addImage(await renderFit(a.w, a.h * 0.86), "JPEG", a.x, a.y, a.w, a.h * 0.86);
      doc.setFontSize(9);
      doc.text(`Parts 2–${total + 1} are the tree at a readable size. Lay them out ${cols} across and ${rows} down, from the top left, row by row.`, a.x, a.y + a.h * 0.9);

      let n = 0;
      for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) {
        n++;
        onProgress?.(`Part ${n} of ${total}…`);
        const x = c * tw, y = r * th;
        const w = Math.min(tw, W - x), h = Math.min(th, H - y);
        if (w < 40 || h < 40) continue;
        const img = await tile(Math.round(x), Math.round(y), Math.ceil(w), Math.ceil(h), Math.min(2.5, 2400 / tw));
        doc.addPage();
        const ar = chrome(doc, page.w, page.h, 1, `Part ${n} of ${total} — row ${r + 1}, column ${c + 1}`, true);
        doc.addImage(img, "JPEG", ar.x, ar.y, w * PX_MM * k, h * PX_MM * k);
        // corner ticks help when joining the sheets
        doc.setDrawColor(...ink); doc.setLineWidth(0.2);
        for (const [cx, cy] of [[ar.x, ar.y], [ar.x + ar.w, ar.y], [ar.x, ar.y + ar.h], [ar.x + ar.w, ar.y + ar.h]] as const) { doc.line(cx - 3, cy, cx + 3, cy); doc.line(cx, cy - 3, cx, cy + 3); }
      }
    });
    await outsidePage(doc, shown);
    onProgress?.("Saving…");
    doc.save(file);
    return file;
  }

  /* ───── poster: one large page (custom size, or a standard A2 / A1 / A0 sheet) ───── */
  onProgress?.("Laying out tree…");
  const file = `family-tree-${tag}-poster${paper === "auto" ? "" : `-${paper}`}.pdf`;
  await withNatural(async ({ W, H, tile }) => {
    let pw: number, ph: number, u: number, mmPerPx: number, ox = 0, oy = 0;
    let doc: InstanceType<typeof jsPDF>, area: { x: number; y: number; w: number; h: number };
    if (paper === "auto") {
      // 1 tree-px = 0.2 mm → a card is ~33 mm wide; keep the page under the PDF limit of 5 m
      mmPerPx = 0.2;
      const headRoom = 1.2;
      while ((W * mmPerPx > 4900 || H * mmPerPx * headRoom > 4900) && mmPerPx > 0.05) mmPerPx -= 0.01;
      pw = Math.max(420, W * mmPerPx);
      u = Math.max(1, pw / 420);
      const probe = chrome(new jsPDF({ unit: "mm", format: [pw, 600 * u] }), pw, 600 * u, u, "");
      ph = H * mmPerPx + (600 * u - probe.h);
      doc = new jsPDF({ orientation: pw >= ph ? "landscape" : "portrait", unit: "mm", format: [pw, ph], compress: true });
      area = chrome(doc, pw, ph, u, subtitle("poster — zoom in on a screen, or take it to a print shop"));
    } else {
      const f = paperFit(paper, W, H, !!viewUrl);
      ({ pw, ph, u, mmPerPx } = f);
      doc = new jsPDF({ orientation: f.landscape ? "landscape" : "portrait", unit: "mm", format: [pw, ph], compress: true });
      area = chrome(doc, pw, ph, u, subtitle(`${PAPER_MM[paper].label} sheet · cards about ${f.cardMm} mm wide`));
      // centre the tree on the sheet when it does not fill it
      ox = (area.w - W * mmPerPx) / 2; oy = Math.max(0, (area.h - H * mmPerPx) / 2);
    }
    // about 170 dpi on paper, whatever the sheet: a small tree on a big sheet needs a bigger picture, a big tree a smaller one
    const s = Math.min(3, Math.max(0.6, 6.5 * mmPerPx));
    const T = Math.min(2400, Math.floor(2700 / s));
    const cols = Math.ceil(W / T), rows = Math.ceil(H / T), total = cols * rows;
    let n = 0;
    for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) {
      n++;
      onProgress?.(`Rendering ${n} of ${total}…`);
      const x = c * T, y = r * T, w = Math.min(T, W - x), h = Math.min(T, H - y);
      doc.addImage(await tile(x, y, w, h, s), "JPEG", area.x + ox + x * mmPerPx, area.y + oy + y * mmPerPx, w * mmPerPx, h * mmPerPx);
    }
    await outsidePage(doc, shown);
    onProgress?.("Saving…");
    doc.save(file);
  });
  return file;
}
